### ISSUE TITLE
load_im_aldb.py sample fails using hub version 1 from windows: 'Serial' object has no attribute 'out_waiting'

### ISSUE THREAD

**Issue by crcowan** [pyinsteon/pyinsteon#371]
When running the load_im_aldb.py sample program from windows I get the following error repeated continuously:

`Exception in callback SerialTransport._poll_write()
handle: <Handle SerialTransport._poll_write()>
Traceback (most recent call last):
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Charles\AppData\Local\Programs\Python\Python310\lib\site-packages\serial_asyncio\__init__.py", line 307, in _poll_write
    if self.serial.out_waiting < self._max_out_waiting:
AttributeError: 'Serial' object has no attribute 'out_waiting'
`
I am running with Pyserial Version: 3.5 and AIOHttp Version: 3.8.4

I am connecting to a hub version 1 on the same network via WIFI.

**Comment by crcowan** [comment]
This issue is resolved with a fix to Pserial. It is in a pull request and it has not yet been accepted: 
https://github.com/pyserial/pyserial/pull/639/commits/74c452070f4586dcd43bb597de6ba0812e12009f
