### ISSUE TITLE
using monitor.py from the command line fails

### ISSUE THREAD

**Issue by rwschul** [pyinsteon/pyinsteon#383]
Can anyone help me please?  I am trying to use the samples/monitor.py utility with a 2245-222 hub and am hitting errors beyond my limited python capabilities...

My secrets.yaml file does include the correct information from the bottom of the hub.

My python:

works# python -V
Python 3.11.2

1.  First of all the original monitor.py had to be modified...
works# diff monitor.py samples/monitor.py
9c9
< USERNAME, PASSWORD, HOST, PORT = get_hub_config()
---
> USERNAME, PASSWORD, HOST = get_hub_config()

2.  Once I corrected this I got some data but then an eventual crash:

works# python ./monitor.py
2023-10-28 12:09:40,669 INFO samples Topic: connection.made data: {}
2023-10-28 12:09:40,669 INFO pyinsteon.protocol.http_transport Insteon Hub reader started
2023-10-28 12:09:41,774 INFO samples Topic: send.get_im_info data: {}
2023-10-28 12:09:41,776 DEBUG pyinsteon.messages TX: msg_id: 0x60
2023-10-28 12:09:42,027 DEBUG pyinsteon.messages RX: msg_id: 0x60, address: 33b610, cat: 0x03, subcat: 0x33, firmware: 0xa5, ack: 0x06
2023-10-28 12:09:42,028 INFO samples Topic: ack.get_im_info data: {'address': 33b610, 'cat': 0x03, 'subcat': 51, 'firmware': 165}
2023-10-28 12:09:42,029 INFO samples Topic: handler.get_im_info data: {'address': 33b610, 'cat': 0x03, 'subcat': 51, 'firmware': 165}
2023-10-28 12:09:42,139 INFO samples Topic: send.get_im_configuration data: {}
2023-10-28 12:09:42,293 DEBUG pyinsteon.messages TX: msg_id: 0x73
2023-10-28 12:09:42,639 DEBUG pyinsteon.messages RX: msg_id: 0x73, flags: {'auto link': 0, 'monitor mode': 1, 'auto led': 0, 'disable deadman': 0}, spare1: 0x01, spare2: 0x00, ack: 0x06
2023-10-28 12:09:42,640 INFO samples Topic: ack.get_im_configuration data: {'disable_auto_linking': False, 'monitor_mode': True, 'auto_led': False, 'deadman': False}
2023-10-28 12:09:42,641 INFO samples Topic: handler.get_im_configuration data: {'disable_auto_linking': False, 'monitor_mode': True, 'auto_led': False, 'deadman': False}
2023-10-28 12:09:42,641 INFO samples Topic: 33b610.modem_config.disable_auto_linking data: {'name': 'disable_auto_linking', 'value': False}
2023-10-28 12:09:42,642 INFO samples Topic: 33b610.modem_config.monitor_mode data: {'name': 'monitor_mode', 'value': True}
2023-10-28 12:09:42,643 INFO samples Topic: 33b610.modem_config.auto_led data: {'name': 'auto_led', 'value': False}
2023-10-28 12:09:42,644 INFO samples Topic: 33b610.modem_config.deadman data: {'name': 'deadman', 'value': False}
2023-10-28 12:09:42,644 ERROR pyinsteon.subscriber_base ListenerMismatchError
2023-10-28 12:09:42,645 ERROR pyinsteon.subscriber_base args: ({'action'},)
2023-10-28 12:09:42,646 ERROR pyinsteon.subscriber_base msg: Listener "device_added" (from module "__main__") inadequate: needs to accept 1 more args (action)
2023-10-28 12:09:42,647 ERROR pyinsteon.subscriber_base module: __main__
2023-10-28 12:09:42,647 ERROR pyinsteon.subscriber_base idStr: device_added
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pyinsteon/utils.py", line 374, in subscribe_topic
    topic.subscribe(listener)
  File "/usr/local/lib/python3.11/dist-packages/pubsub/core/topicobj.py", line 356, in subscribe
    argsInfo = self.__validator.validate(listener, curriedArgNames=curriedArgs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pubsub/core/listener.py", line 274, in validate
    self.__validateArgs(listener, paramsInfo, curriedArgNames)
  File "/usr/local/lib/python3.11/dist-packages/pubsub/core/listener.py", line 300, in __validateArgs
    raise ListenerMismatchError(msg, listener, missingParams)
pubsub.core.callables.ListenerMismatchError: Listener "device_added" (from module "__main__") inadequate: needs to accept 1 more args (action)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pubsub/core/topicutils.py", line 99, in stringize
    name = '.'.join(topicName)
           ^^^^^^^^^^^^^^^^^^^
TypeError: can only join an iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/INSTEON/pyinsteon/pyinsteon-dev/works/./monitor.py", line 39, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/INSTEON/pyinsteon/pyinsteon-dev/works/./monitor.py", line 20, in run
    devices.subscribe(device_added)
  File "/usr/local/lib/python3.11/dist-packages/pyinsteon/subscriber_base.py", line 29, in subscribe
    subscribe_topic(callback, self._subscriber_topic, _LOGGER)
  File "/usr/local/lib/python3.11/dist-packages/pyinsteon/utils.py", line 381, in subscribe_topic
    for topic_listner in pub.getDefaultTopicMgr().getTopic(topic).getListeners():
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pubsub/core/topicmgr.py", line 146, in getTopic
    topicNameDotted = stringize(name)
                      ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pubsub/core/topicutils.py", line 102, in stringize
    raise TopicNameError(topicName, str(exc))
pubsub.core.topicexc.TopicNameError: Topic name "device_list_changed(1)": can only join an iterable

What else does "device_added" need?  I'm speculating that it was passed an empty string and that the "iterable" problem will go away if that is fixed.

Any help would be appreciated.

Thanks

**Comment by rwschul** [comment]
Answering my own question... 

First, in all places (and there are lots)...
Update this:  USERNAME, PASSWORD, HOST = get_hub_config()
to this:          USERNAME, PASSWORD, HOST, PORT = get_hub_config()

Second, also in a lot of places but specifically in monitor.py
Update this: def device_added(address):
to this:         def device_added(action, address):

I now get a constant stream of data from the hub when I run monitor.py.  

I am leaving this open so that someone can eventually look at it and do the right things in github to make the samples work properly.

**Comment by teharris1** [comment]
There is an easier way to go into monitoring mode. You can use the `insteon_tools` command or you can run `python3 -m pyinsteon`. This will create a command line interface that you can use to interact with devices and the modem.  To run monitor mode you would use the following commands:
```
connect <connection options>
set_log_level <logging options>
monitor_mode
```
The connection options are as follows:
PLM:
   - connect /dev/ttyUSB0
Hub v1:
   - connect 192.168.1.100
 Hub v2: 
   - connect 192.168.1.100 my_user

With the Hub v2 you will be prompted for a password.

For the logging options you can use the following:
- `i`: Information messages only - lowest level of logging
- `m`: Insteon messages - Technical view of byte level messages to and from devices
- `t`: pyinsteon topics - Extensive monitoring that will show the end to end message handling 
- `d`: Full debug level - Not much more than the `t` option 

There is another command `log_to_file` that records all of the log messages to a file based on the log level set above. Finally, you can use the `help` command to see what commands are available.

This is something I have been thinking of documenting but since the tool was used primarily for my development purposes and to debug the application I have not taken the time to document it.

**Comment by rwschul** [comment]
Thanks a lot for your response.  I don't want to actually interact with the hub.  I want to pipe the logs to a follow on process which is why I was looking at monitor.py in the first place.  But being able to log to a file is fine too then I just monitor the file for changes.

It's all very hackerish but I am building a local only home automation system around a few raspberry pi's and ha_bridge.  I have wiz lights... that have some pretty cool undocumented capabilities, x10 motion sensors, and insteon switches.  Haha... I think I am the only person who can successfully turn on the kitchen lights.
