### ISSUE TITLE
I/O Linc [2450] sensor state change seems to cause an error in pyinsteon

### ISSUE THREAD

**Issue by jdscavo** [pyinsteon/pyinsteon#422]
Maybe this should be posted somewhere else? Noticed the log errors are referring to pyinsteon, so starting here. 

Not sure if there is any correlation to this, but around home assistant core release 202460, the sensor status from this device stopped working. Using the old Home Linc software to monitor hub activity, I can see the sensor state is changing on the Insteon network. Looking at Home assistant logs some errors are being produced during the sensor change. Nothing recorded in the logs prior to the state change or after the last log entry:

2024-07-02 14:02:42.183 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyinsteon/device_types/sensors_actuators.py", line 323, in _async_on_off_received
    await self.async_status(group=0)
  File "/usr/local/lib/python3.12/site-packages/pyinsteon/device_types/sensors_actuators.py", line 143, in async_status
    status_type = self._groups[group].status_type if group is not None else None
                  ~~~~~~~~~~~~^^^^^^^
KeyError: 0

Relay control on this device is working fine. Have not noticed issues with with the other 18 devices and 27 entities in the Home assistant Insteon integration. I noticed immediately when the sensor state stopped working since it iss part of an automation to turn on some lights and unlock a door when the state changes. 

Thanks.

**Comment by connorgallopo** [comment]
This was resolved in 1.6.3
