### ISSUE TITLE
Error with insteon.load_all_link_database

### ISSUE THREAD

**Issue by jlambert121** [pyinsteon/pyinsteon#63]
I'm not sure if this is the right place to post this or not, please let me know if there is a better place.

I have must moved my PLM over from an indigo box to a raspberry PI running HA and was attempting to load all devices from the PLM.

When running `` with

```
entity_id: all
reload: true
```

I get this in HA:

```
/usr/local/lib/python3.8/site-packages/pyinsteon/aldb/__init__.py:63: RuntimeWarning: coroutine 'async_register_services.<locals>.async_srv_save_devices' was never awaited
  callback()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2020-12-27 08:18:38 ERROR (MainThread) [frontend.js.latest.202012120] https://myname.duckdns.org:8123/frontend_latest/chunk.6b18c64ed740014d3f00.js:1:8122 YAMLException: unacceptable kind of an object to dump [object Undefined]
```

I grabbed the JSON from `/config/insteon_devices.json` and ran it through a parser just to make sure there weren't any exceptions there.  I'm not sure which YAML this error is referring to though to go check that out.

Previously I was getting these errors when I had run the import first (which did import a bunch of devices, but not all)

```
2020-12-27 07:47:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/managers/device_manager.py", line 222, in async_setup_device
    await device.async_add_default_links()
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/device_types/device_base.py", line 224, in async_add_default_links
    return await async_add_default_links(self)
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/managers/link_manager/default_links.py", line 39, in async_add_default_links
    result = await async_link_devices(
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/managers/link_manager/__init__.py", line 53, in async_link_devices
    _, failed_2 = await responder.aldb.async_write()
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/aldb/aldb_base.py", line 272, in async_write
    for mem_addr in self._dirty_records:
RuntimeError: dictionary changed size during iteration
```

I removed and re-added the insteon integration and it still has the 24 devices previously found and attempting to run `insteon.load_all_link_database` doesn't give any different results after that.

**Comment by jlambert121** [comment]
I was able to get all devices loading by just interacting or putting them into discovery mode.  I have a few more errors in the logs though, not sure if they're of any concern or not though.

```
2020-12-27 11:37:15 ERROR (MainThread) [pyinsteon.utils] An issue occured distributing the following message
2020-12-27 11:37:15 ERROR (MainThread) [pyinsteon.utils] MSG: 02514cb16f34788c152f0000010fe700e20434788c031f009a
2020-12-27 11:37:15 ERROR (MainThread) [pyinsteon.utils] Topic: 4cb16f.extended_read_write_aldb.direct data: {'cmd1': 47, 'cmd2': 0, 'target': 34788c, 'user_data': 00.01.0f.e7.00.e2.04.34.78.8c.03.1f.00.9a, 'hops_left': 1}
2020-12-27 11:37:15 ERROR (MainThread) [pyinsteon.utils] Error: BUG: Dead Listener called, still subscribed!
2020-12-27 12:11:59 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/device_types/battery_base.py", line 128, in _ensure_commands
    return await self._run_commands()
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/device_types/battery_base.py", line 142, in _run_commands
    _LOGGER.debug(str(command))
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/aldb/aldb_base.py", line 65, in __repr__
    return ", ".join("%s: %r" % item for item in attrs.items())
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/aldb/aldb_base.py", line 65, in <genexpr>
    return ", ".join("%s: %r" % item for item in attrs.items())
  File "/usr/local/lib/python3.8/site-packages/pyinsteon/aldb/aldb_record.py", line 64, in __repr__
    "data1": f"0x{self.data1:02x}",
  File "/usr/local/lib/python3.8/enum.py", line 669, in __format__
    return cls.__format__(val, format_spec)
ValueError: Unknown format code 'x' for object of type 'str'
2020-12-27 12:46:10 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
```

**Comment by teharris1** [comment]
This should be fixed by the way. Please let me know if you still have this issue.

**Comment by teharris1** [comment]
Nevermind, the original issue was not fixed but the issue in your second commend was fixed. 

The first issue will be fixed in the next release of pyinsteon.
