### ISSUE TITLE
Initial startup RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by mstovenour** [pyinsteon/pyinsteon#72]
I've been using python-insteonplm with HA v1.105 for a very long time and it has worked well.  Today I finally found the courage to try the new pyinsteon library.  On the very initial startup I encountered the traceback below.  It was repeated multiple times.  The full log output can be found in this gist https://gist.github.com/mstovenour/fafd9b72870e7234aa76d2983a37f9c3.  I have logs set globally to info.  I've left the system in this state with out restarting or performing any other actions in HA.  What do you suggest for the next steps to debug this issue?

Attribute | Value
-- | --
Version | core-2021.2.3
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 4.19.0-14-amd64
CPU Architecture | x86_64

```
bash-5.0# more /usr/src/homeassistant/homeassistant/components/insteon/manifest.json
{
  "domain": "insteon",
  "name": "Insteon",
  "documentation": "https://www.home-assistant.io/integrations/insteon",
  "requirements": ["pyinsteon==1.0.8"],
  "codeowners": ["@teharris1"],
  "config_flow": true
}
```

```
...
2021-02-25T13:35:47.681321616Z 2021-02-25 07:35:47 INFO (MainThread) [pyinsteon.managers.device_manager] Adding device to INSTEON devices list: 37f42e
2021-02-25T13:38:15.693845479Z 2021-02-25 07:38:15 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.insteon entity: switch.on_off_outdoor_module_37_f4_2e
2021-02-25T13:40:32.748218989Z 2021-02-25 07:40:32 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.insteon entity: switch.keypadlinc_on_off_20_42_d3_main
2021-02-25T13:40:32.748245328Z 2021-02-25 07:40:32 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.insteon entity: switch.keypadlinc_on_off_20_42_d3_button_a
2021-02-25T13:40:32.749351557Z 2021-02-25 07:40:32 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.insteon entity: switch.keypadlinc_on_off_20_42_d3_button_b
2021-02-25T13:40:32.749382996Z 2021-02-25 07:40:32 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.insteon entity: switch.keypadlinc_on_off_20_42_d3_button_c
2021-02-25T13:40:32.749493404Z 2021-02-25 07:40:32 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.insteon entity: switch.keypadlinc_on_off_20_42_d3_button_d
2021-02-25T13:41:58.204982754Z 2021-02-25 07:41:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
2021-02-25T13:41:58.205063502Z Traceback (most recent call last):
2021-02-25T13:41:58.205080286Z   File "/usr/local/lib/python3.8/site-packages/pyinsteon/managers/device_manager.py", line 222, in async_setup_device
2021-02-25T13:41:58.205093101Z     await device.async_add_default_links()
2021-02-25T13:41:58.205106151Z   File "/usr/local/lib/python3.8/site-packages/pyinsteon/device_types/device_base.py", line 224, in async_add_default_links
2021-02-25T13:41:58.205119347Z     return await async_add_default_links(self)
2021-02-25T13:41:58.205130939Z   File "/usr/local/lib/python3.8/site-packages/pyinsteon/managers/link_manager/default_links.py", line 39, in async_add_default_links
2021-02-25T13:41:58.205143037Z     result = await async_link_devices(
2021-02-25T13:41:58.205154018Z   File "/usr/local/lib/python3.8/site-packages/pyinsteon/managers/link_manager/__init__.py", line 53, in async_link_devices
2021-02-25T13:41:58.205166527Z     _, failed_2 = await responder.aldb.async_write()
2021-02-25T13:41:58.205178044Z   File "/usr/local/lib/python3.8/site-packages/pyinsteon/aldb/aldb_base.py", line 272, in async_write
2021-02-25T13:41:58.205189736Z     for mem_addr in self._dirty_records:
2021-02-25T13:41:58.205205973Z RuntimeError: dictionary changed size during iteration
...
```

**Comment by mstovenour** [comment]
The problem did not reoccur the second time I started HA.  Probably because the PLM ALDB was already cached.

**Comment by teharris1** [comment]
This appears to be some type of race condition. You are correct that the second start would use the cached entries. But after a number of full start-ups during testing I have not seen this behavior.
________________________________

**Comment by mstovenour** [comment]
I'll try to reproduce it with debug level logging to see if we catch any additional information.  I have a dev environment configured with vscode and the remote docker plugin so I should be able to place a break point and look around once I have a better idea of how the initialization sequence unfolds.
